server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identityService
    username: root
    password: 392002
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
    signerKey: "81e3c0c23fe15c1d0d7fa08252102bf59fe100998e3848a10e23cfd5df605dac"